from commands.cmd_balance import cmd_balance
from commands.cmd_clear import cmd_clear
from commands.cmd_gamble import cmd_gamble
from commands.cmd_join import cmd_join
from commands.cmd_mine import cmd_mine
from commands.cmd_ore import cmd_ore
from commands.cmd_pay import cmd_pay
from commands.cmd_quit import cmd_quit
from commands.cmd_register import cmd_register
